name: anchor-test
on: [push]
env:
  AVM_VERSION: 0.24.2
  ANCHOR_VERSION: 0.24.2
  SOLANA_CLI_VERSION: 1.10.32
jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        run: yarn
        shell: bash
      - name: Cache Solana tool suite
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-build-${{ env.SOLANA_CLI_VERSION }}
      - name: Install Solana tool suite
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
        shell: bash
      - name: Update PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH 
        shell: bash
      - name: Create keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - name: Install necessary packages
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
      # - uses: actions/cache@v2
      #   name: Cache AVM
      #   id: cache-avm
      #   with:
      #     path: ~/.cargo/bin
      #     key: avm-${{ runner.os }}-build-${{ env.AVM_VERSION }}
      # - name: Install AVM
      #   run: cargo install --git https://github.com/project-serum/anchor avm --locked --tag v${{ env.AVM_VERSION }}
      # - name: Cache Anchor
      #   uses: actions/cache@v2
      #   id: cache-anchor
      #   with:
      #     path: ~/.avm
      #     key: anchor-${{ runner.os }}-build-${{ env.ANCHOR_VERSION }}
      # - name: Install Anchor
      #   run: avm install ${{ env.ANCHOR_VERSION }}
      #   shell: bash
      # - name: Activate Anchor
      #   run: avm use ${{ env.ANCHOR_VERSION }}
      #   shell: bash
      # - name: Verify version
      #   run: anchor --version
        # shell: bash
      # - name: Cache Anchor
      #   uses: actions/cache@v2
      #   id: cache-anchor
      #   with:
      #     path: ~/.cargo/bin
      #     key: anchor-${{ runner.os }}-build-${{ env.ANCHOR_VERSION }}
      # - name: Install Anchor
      #   run: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked
      - name: Install Anchor
        run: npm i -g @project-serum/anchor-cli@${{ env.ANCHOR_VERSION }}
      - name: Make Anchor.toml file compatible with runner
        run: sed -i 's/user/runner/' Anchor.toml
        shell: bash
      - name: Run tests
        run: anchor test 

