name: anchor-test
on: [push]
jobs:
  run-anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Anchor Test
        uses: mrgnlabs/anchor-test-action@v0.4
        with:
          args: ""
          workspace_dir: "."

