name: anchor-test
on: [push]
env:
  AVM_VERSION: 0.24.2
  ANCHOR_VERSION: 0.24.2
  SOLANA_CLI_VERSION: 1.10.32
jobs:
  run-anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        run: yarn
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}
      - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
        shell: bash
      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH 
        shell: bash
      - run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - name: Install necessary packages
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
      - uses: actions/cache@v2
        name: Cache AVM
        id: cache-avm
        with:
          path: ~/.cargo/bin
          key: avm-${{ runner.os }}-build-${{ env.AVM_VERSION }}
      - name: Install AVM
        run: cargo install --git https://github.com/project-serum/anchor avm --locked --tag v${{ env.AVM_VERSION }}
      - name: Cache Anchor
        uses: actions/cache@v2
        id: cache-anchor
        with:
          path: ~/.avm
          key: anchor-${{ runner.os }}-build-${{ env.ANCHOR_VERSION }}
      - name: Install Anchor
        run: avm install ${{ env.ANCHOR_VERSION }}
      - name: Activate Anchor
        run: avm use ${{ env.ANCHOR_VERSION }}
      - name: Verify version
        run: anchor --version
      - name: Run tests
        run: anchor test

